### ISSUE TITLE
Goals of lucuma?

### ISSUE THREAD

**Issue by myguidingstar** [jeluard/lucuma#53]
Hi @jeluard 
Components are all about reusability. Does lucuma intend to:
 - support using/importing existing (plain javascript) components?
 - support producing components that can be used in plain javascript projects?

I looked in to example project but couldn't find the anwser myself
Thanks

**Comment by jeluard** [comment]
The goal of lucuma is to allow the creation of first class citizen html element, like the newish `dialog` or `picture` backed by ClojureScript code.
As your components are then plain html elements you can manipulate them from JavaScript as any html element.

Does that answer your question?

**Comment by myguidingstar** [comment]
Got it. What about using not-made-by-Lucuma components inside Lucuma ones?

**Comment by jeluard** [comment]
Do you have any specific components in mind? In general I don't plan anything specific beyond Web Components standard and plan JavaScript usage.
